# First remove *all* keybindings
# unbind-key -a
# Now reinsert all the regular tmux keys
bind ^X lock-server
bind ^C new-window -c "$HOME"
bind ^D detach
bind * list-clients

bind H previous-window
bind L next-window

bind r command-prompt "rename-window %%"
bind R source-file ~/.config/tmux/tmux.conf \; display-message "conf reloaded"
bind a last-window
bind-key C-a send-key C-a
bind ^W list-windows
bind w list-windows
bind z resize-pane -Z
bind ^L refresh-client
bind l refresh-client
bind | split-window
bind s split-window -v -c "#{pane_current_path}" \; send-keys "open_current_project_container.sh || clear " Enter
bind v split-window -h -c "#{pane_current_path}" \; send-keys "open_current_project_container.sh || clear " Enter
bind '"' choose-window
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -r -T prefix , resize-pane -L 20
bind -r -T prefix . resize-pane -R 20
bind -r -T prefix - resize-pane -D 7
bind -r -T prefix = resize-pane -U 7
bind : command-prompt
bind X setw synchronize-panes
bind P set pane-border-status
bind K kill-pane
#bind x swap-pane -D
bind S choose-session
bind Enter copy-mode
# bind -T copy-mode MouseDragEnd1Pane send -X copy-selection-no-clear 'pbcopy'
unbind -T copy-mode-vi MouseDragEnd1Pane


unbind -T copy-mode-vi v
bind -T copy-mode-vi v send -X begin-selection     # Begin selection in copy mode.
bind -T copy-mode-vi C-v send -X rectangle-toggle  # Begin selection in copy mode.
bind -T copy-mode-vi y send -X copy-selection      # Yank selection in copy mode.
